add backoff to hasura

diff --git a/serverless-deploy/action.yml b/serverless-deploy/action.yml
--- a/serverless-deploy/action.yml
+++ b/serverless-deploy/action.yml
@@ -129,11 +129,16 @@ runs:
         until hasura metadata apply --admin-secret $HASURA_ADMIN_SECRET --endpoint "https://$HASURA_ENDPOINT" --skip-update-check; do
           ((RETRIES--))
           if [ $RETRIES -le 0 ]; then
-           echo "Hasura metadata apply failed after multiple attempts"
-           exit 1
+            echo "Hasura metadata apply failed after multiple attempts"
+            exit 1
           fi
+          rm ./.env
+          aws s3 cp s3://acutity-env/backend/${{ inputs.ENVIRONMENT}} ./.env
+          set -o allexport
+          source .env
+          set +o allexport
           echo "Retrying Hasura metadata apply ($RETRIES retries left)"
-          sleep 5
+          sleep 5  # Sleep for 5 seconds before retrying
         done
     - name: Post to a Slack channel
       id: slack
